
~~~~~~~~~~ GROUP 12 REPORT ~~~~~~~~~~
test_add1_command (__main__.TestSalesDataImporter.test_add1_command) ... FAIL
test_add2_command (__main__.TestSalesDataImporter.test_add2_command) ... FAIL
test_exit_command (__main__.TestSalesDataImporter.test_exit_command) ... FAIL
test_import_command (__main__.TestSalesDataImporter.test_import_command) ... FAIL
test_invalid_menu_command (__main__.TestSalesDataImporter.test_invalid_menu_command) ... FAIL
test_menu_command (__main__.TestSalesDataImporter.test_menu_command) ... FAIL
test_view_command (__main__.TestSalesDataImporter.test_view_command) ... FAIL

======================================================================
FAIL: test_add1_command (__main__.TestSalesDataImporter.test_add1_command)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\sandy\csci6163_20252_sp\g12_sp\p01_files\tests\test_app-1.py", line 83, in test_add1_command
    self.assertIn("Sales for 2021-02-14 is added.\n", stdout)
AssertionError: 'Sales for 2021-02-14 is added.\n' not found in ''

======================================================================
FAIL: test_add2_command (__main__.TestSalesDataImporter.test_add2_command)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\sandy\csci6163_20252_sp\g12_sp\p01_files\tests\test_app-1.py", line 93, in test_add2_command
    self.assertIn("Sales for 2021-08-14 is added.\n", stdout)
AssertionError: 'Sales for 2021-08-14 is added.\n' not found in ''

======================================================================
FAIL: test_exit_command (__main__.TestSalesDataImporter.test_exit_command)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\sandy\csci6163_20252_sp\g12_sp\p01_files\tests\test_app-1.py", line 54, in test_exit_command
    self.assertIn("Saved sales records.\nBye!\n", stdout)
AssertionError: 'Saved sales records.\nBye!\n' not found in ''

======================================================================
FAIL: test_import_command (__main__.TestSalesDataImporter.test_import_command)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\sandy\csci6163_20252_sp\g12_sp\p01_files\tests\test_app-1.py", line 101, in test_import_command
    self.assertIn("Imported sales added to list.", stdout)
AssertionError: 'Imported sales added to list.' not found in ''

======================================================================
FAIL: test_invalid_menu_command (__main__.TestSalesDataImporter.test_invalid_menu_command)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\sandy\csci6163_20252_sp\g12_sp\p01_files\tests\test_app-1.py", line 64, in test_invalid_menu_command
    self.assertIn("Invalid command. Please try again.\n\nCOMMAND MENU\n", stdout)
AssertionError: 'Invalid command. Please try again.\n\nCOMMAND MENU\n' not found in ''

======================================================================
FAIL: test_menu_command (__main__.TestSalesDataImporter.test_menu_command)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\sandy\csci6163_20252_sp\g12_sp\p01_files\tests\test_app-1.py", line 59, in test_menu_command
    self.assertIn("COMMAND MENU\n", stdout)
AssertionError: 'COMMAND MENU\n' not found in ''

======================================================================
FAIL: test_view_command (__main__.TestSalesDataImporter.test_view_command)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\sandy\csci6163_20252_sp\g12_sp\p01_files\tests\test_app-1.py", line 70, in test_view_command
    self.assertIn("Date", stdout)
AssertionError: 'Date' not found in ''

----------------------------------------------------------------------
Ran 7 tests in 0.137s

FAILED (failures=7)
